### ISSUE TITLE
How to provision apiToken?

### ISSUE THREAD

**Issue by vshuraeff** [apricote/grafana-hcloud-datasource#8]
Hi! 
I use provisioned DataSources via `docker-compose` and include file like this
```yaml
  - name: HetznerCloud
    type: 'apricote-hcloud-datasource'
    access: proxy
    isDefault: false
    orgId: 1
    version: 1
    secureJsonData:
      apiToken: ${HETZNER_CLOUD_TOKEN}
```
But it's not working =(
How I should do this right way?
Moreover, if I paste working API Toket to field, I've got an error:

`API Token was not configured or does not work, a valid API Token is required for the data source to access the Hetzner Cloud API` 

How to diagnose what's going wrong?
In Grafana Logs, after pressing Test button I see only this:
`logger=context userId=1 orgId=1 uname=admin t=2024-08-07T13:30:12.529959137Z level=info msg="Request Completed" method=GET path=/api/datasources/uid/PC8C36DBD0101EDFD/health status=400 remote_addr=192.168.65.1 time_ms=311 duration=311.669667ms size=159 referer=http://localhost:3000/connections/datasources/edit/PC8C36DBD0101EDFD handler=/api/datasources/uid/:uid/health status_source=server`

**Comment by apricote** [comment]
Can you test the following?

1. Enable debug logging in the data source settings (Under _"Development > Options"_)
2. Paste in the token
3. Test
4. Check the Grafana Logs again

You should see a request being made to the Hetzner Cloud API. Can you share that here?

**Comment by vshuraeff** [comment]
I can't enable Debug, I assume this is because this datasource is provisioned.
Of course I've tried to enable Debug, but nothing happen.

**Comment by civodul999** [comment]
Hi,
I have done this way : 

```
  - name: Hetzner
    type: apricote-hcloud-datasource
    access: proxy
    url: https://api.hetzner.cloud/v1
    secureJsonData:
      token: '<token>'
    jsonData:
      Access-Control-Allow-Headers: X-Requested-With,Authorization,Content-Type
      Access-Control-Allow-Methods: OPTIONS,GET,POST,PUT,PATCH,DELETE
      Access-Control-Allow-Origin: *
      Access-Control-Expose-Headers: Link,X-Correlation-ID
      Access-Control-Max-Age: 86400
      Content-Type: application/json
    isDefault: false
    version: 1
    editable: true
```
